/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Entidades.Coordenadores;
import Entidades.Cursos;

import com.sun.javafx.tk.Toolkit;
import dados.DadosException;
import java.awt.Component;
import java.io.File;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import negocio.CoordenadoresBO;
import negocio.CursosBO;

import negocio.NegocioException;


/**
 *
 * @author Wallace
 */
public class JFICursos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFICursos
     */
   
    
    public JFICursos() {
        super();
        initComponents();

       Component[] componentes =  this.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(false);
        if (componente instanceof JTextField) {
              //apaga os valores
              JTextField field = (JTextField) componente;
              field.setText("");
              
            }    
           
    } 
              CoordenadoresBO bo=new CoordenadoresBO();
                            cmbcoordenador.removeAllItems();
                            try{
                                List<Coordenadores> lista=bo.listar();
                                for(Coordenadores lstcoordenadores:lista){

                                //Object[] linha = //alguma linha

                                //model.addRow(linha);
                                    
                                    cmbcoordenador.addItem(lstcoordenadores.getNomecord());
                                }
                            }catch(NegocioException ex){

                            }
      btnnovo.setEnabled(true);    
      btnconsultar.setEnabled(true);
       btncancelar.setEnabled(false);
       btnalterar.setEnabled(false);
     
    }
public void mostraunidades(){

  
}
public void mostraempresas(){
  
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Geral = new javax.swing.JPanel();
        JpanelCursos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttpcurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmodalidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        txtdenominacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txthabilitacao = new javax.swing.JTextField();
        txtlocaloferta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtturnos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtvagas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcargahoraria = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtregime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtperiodos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        txttitulacao = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtdedicacao = new javax.swing.JTextField();
        btnsalvar = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        cmbcoordenador = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnnovo = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jFIPPC1 = new Apresentacao.JFIPPC();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Incluir Dados Gerais do Curso");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        Geral.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GeralformFocusGained(evt);
            }
        });
        Geral.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                GeralformComponentShown(evt);
            }
        });

        JpanelCursos.setEnabled(false);

        jLabel2.setText("Modalidade:");

        txttpcurso.setEnabled(false);

        jLabel3.setText("Denominação do Curso:");

        txtmodalidade.setEnabled(false);

        jLabel1.setText("Tipo de Curso:");

        lblid.setText(" ");
        lblid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblidInputMethodTextChanged(evt);
            }
        });

        txtdenominacao.setEnabled(false);

        jLabel5.setText("Habilitação:");

        txthabilitacao.setEnabled(false);
        txthabilitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthabilitacaoActionPerformed(evt);
            }
        });

        txtlocaloferta.setEnabled(false);

        jLabel7.setText("Local de Oferta:");

        jLabel8.setText("Turnos de Funcionamento:");

        txtturnos.setEnabled(false);

        jLabel9.setText("Numero de vagas para cada Turno ");

        txtvagas.setEnabled(false);

        jLabel10.setText("Vagas Anuais");

        jLabel11.setText("Carga Horária do Curso:");

        txtcargahoraria.setEnabled(false);
        txtcargahoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcargahorariaActionPerformed(evt);
            }
        });

        jLabel12.setText("Horas");

        jLabel13.setText("Estrutura Curricular:");

        jLabel14.setText("Regime Letivo:");

        txtregime.setEnabled(false);

        jLabel15.setText("Períodos");

        txtperiodos.setEnabled(false);

        jLabel16.setText("Coordenador do Curso:");

        jLabel17.setText("Nome:");

        jLabel18.setText("CPF:");

        txtcpf.setEnabled(false);

        txttitulacao.setEnabled(false);

        jLabel19.setText("Titulação:");

        jLabel20.setText("Tempo de Dedicação:");

        txtdedicacao.setEnabled(false);

        btnsalvar.setText("SALVAR");
        btnsalvar.setEnabled(false);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnalterar.setText("ALTERAR");
        btnalterar.setEnabled(false);
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btncancelar.setText("LIMPAR");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        cmbcoordenador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbcoordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcoordenadorActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Cadastrar Novo Coordenador");

        btnnovo.setText("NOVO");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        btnconsultar.setText("CONSULTAR");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        jLabel6.setText("ID Curso:");

        jFIPPC1.setVisible(true);

        javax.swing.GroupLayout JpanelCursosLayout = new javax.swing.GroupLayout(JpanelCursos);
        JpanelCursos.setLayout(JpanelCursosLayout);
        JpanelCursosLayout.setHorizontalGroup(
            JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JpanelCursosLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtdenominacao))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JpanelCursosLayout.createSequentialGroup()
                            .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFIPPC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txttpcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtmodalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JpanelCursosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthabilitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlocaloferta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelCursosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(JpanelCursosLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JpanelCursosLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdedicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelCursosLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtturnos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtvagas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addGroup(JpanelCursosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtcargahoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addComponent(jLabel13)
                    .addGroup(JpanelCursosLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtregime, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtperiodos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16)
                    .addGroup(JpanelCursosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(cmbcoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelCursosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnovo)
                .addGap(18, 18, 18)
                .addComponent(btnsalvar)
                .addGap(29, 29, 29)
                .addComponent(btnconsultar)
                .addGap(27, 27, 27)
                .addComponent(btnalterar)
                .addGap(18, 18, 18)
                .addComponent(btncancelar)
                .addGap(179, 179, 179))
        );
        JpanelCursosLayout.setVerticalGroup(
            JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelCursosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttpcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtmodalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdenominacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txthabilitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtlocaloferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtturnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtvagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtcargahoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtregime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtperiodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbcoordenador)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txttitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtdedicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JpanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalvar)
                    .addComponent(btnalterar)
                    .addComponent(btncancelar)
                    .addComponent(btnnovo)
                    .addComponent(btnconsultar)))
            .addGroup(JpanelCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFIPPC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GeralLayout = new javax.swing.GroupLayout(Geral);
        Geral.setLayout(GeralLayout);
        GeralLayout.setHorizontalGroup(
            GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeralLayout.createSequentialGroup()
                .addComponent(JpanelCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(969, 969, 969))
        );
        GeralLayout.setVerticalGroup(
            GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeralLayout.createSequentialGroup()
                .addComponent(JpanelCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2937, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Geral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Geral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        Cursos curso= new Cursos();
        curso.setTpcurso(txttpcurso.getText());
        curso.setCargahoraria(Integer.parseInt(txtcargahoraria.getText()));
        curso.setModalidade(txtmodalidade.getText());
        curso.setDenomincacao(txtdenominacao.getText());
        curso.setHabilitacao(txthabilitacao.getText());
        curso.setLocaloferta(txtlocaloferta.getText());
        curso.setTurnos(Integer.parseInt(txtturnos.getText().toString()));
        curso.setVagas(Integer.parseInt(txtvagas.getText()));
        curso.setRegine(txtregime.getText());
        curso.setPeriodos(Integer.parseInt(txtperiodos.getText()));
        curso.setCoordenador(cmbcoordenador.getSelectedItem().toString());
        curso.setCpfcoord(txtcpf.getText());
        curso.setTitulacao(txttitulacao.getText());
        JOptionPane.showMessageDialog(null, txtturnos.getText());
        CursosBO bo = new CursosBO();
        try{
          
                bo.inserir(curso);
                    Component[] componentes =   JpanelCursos.getComponents(); // altere para o nome da variavel do seu painel
          /*  for (Component componente : componentes) {
                componente.setEnabled(false);
                if (componente instanceof JTextField) {
                  //apaga os valores
                  JTextField field = (JTextField) componente;
                  field.setText("");

                }
            }*/    
           btnnovo.setEnabled(true);              
           btncancelar.setEnabled(false);
           btnconsultar.setEnabled(true);
           btnalterar.setEnabled(false);
            btnsalvar.setEnabled(false);
        }catch(NegocioException e){
            JOptionPane.showMessageDialog(null,e.getMessage() ,"Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
            
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        // TODO add your handling code here:

        Cursos curso= new Cursos();
        curso.setIdcurso(Integer.parseInt(lblid.getText()));
        curso.setTpcurso(txttpcurso.getText());
        curso.setCargahoraria(Integer.parseInt(txtcargahoraria.getText()));
        curso.setModalidade(txtmodalidade.getText());
        curso.setDenomincacao(txtdenominacao.getText());
        curso.setHabilitacao(txthabilitacao.getText());
        curso.setLocaloferta(txtlocaloferta.getText());
        curso.setTurnos(Integer.parseInt(txtturnos.getText()));
        curso.setVagas(Integer.parseInt(txtvagas.getText()));
        curso.setRegine(txtregime.getText());
        curso.setPeriodos(Integer.parseInt(txtperiodos.getText()));
        curso.setCoordenador(cmbcoordenador.getSelectedItem().toString());
        curso.setCpfcoord(txtcpf.getText());
        curso.setTitulacao(txttitulacao.getText());
 JOptionPane.showMessageDialog(null, txtturnos.getText());
        CursosBO bo = new CursosBO();
        try{
          
                bo.alterar(curso);
        Component[] componentes =  this.JpanelCursos.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(false);
            if (componente instanceof JTextField) {
              //apaga os valores
              JTextField field = (JTextField) componente;
              field.setText("");
              
            }
        }    
           txtcpf.setEnabled(false);
           txttitulacao.setEnabled(false);
           txtdedicacao.setEnabled(false);
           btnnovo.setEnabled(true);              
           btncancelar.setEnabled(false);
           btnconsultar.setEnabled(true);
           btnalterar.setEnabled(false);
            btnsalvar.setEnabled(false);
        }catch(NegocioException e){
            JOptionPane.showMessageDialog(null,e.getMessage() ,"Aviso", JOptionPane.WARNING_MESSAGE);
        }   
       
    }//GEN-LAST:event_btnalterarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here
                        // altere para o nome da variavel do seu painel
        Component[] componentes =   JpanelCursos.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(false);
            if (componente instanceof JTextField) {
              //apaga os valores
              JTextField field = (JTextField) componente;
              field.setText("");
              
            }
        }    
       btnnovo.setEnabled(true);              
       btncancelar.setEnabled(false);
       btnalterar.setEnabled(false);
       btnconsultar.setEnabled(true);
        btnsalvar.setEnabled(false);
    }//GEN-LAST:event_btncancelarActionPerformed
    
    private void GeralformFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GeralformFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_GeralformFocusGained

    private void GeralformComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_GeralformComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_GeralformComponentShown

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
         
                  
        
            
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtcargahorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcargahorariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcargahorariaActionPerformed

    private void lblidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblidInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_lblidInputMethodTextChanged

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        // TODO add your handling code here:
        Component[] componentes =  this.JpanelCursos.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(true);
            if (componente instanceof JTextField) {
              //apaga os valores
              JTextField field = (JTextField) componente;
              field.setText("");
              
            }
        }
           CoordenadoresBO bo=new CoordenadoresBO();
                            cmbcoordenador.removeAllItems();
                            try{
                                List<Coordenadores> lista=bo.listar();
                                for(Coordenadores lstcoordenadores:lista){

                                //Object[] linha = //alguma linha

                                //model.addRow(linha);
                                    
                                    cmbcoordenador.addItem(lstcoordenadores.getNomecord());
                                }
                            }catch(NegocioException ex){

                            }
      btnnovo.setEnabled(false);    
      btnconsultar.setEnabled(false);
       btncancelar.setEnabled(true);
       btnalterar.setEnabled(false);
       txtcpf.setEnabled(false);
            txtdedicacao.setEnabled(false);
            txtdedicacao.setEnabled(false);
    }//GEN-LAST:event_btnnovoActionPerformed

    private void txthabilitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthabilitacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthabilitacaoActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
         int idconsulta = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da Curso"));
        CursosBO bo = new CursosBO();
        try {
           
            Cursos curso=bo.consultar(idconsulta);
            lblid.setText(String.valueOf(curso.getIdcurso()));
            txttpcurso.setText(curso.getTpcurso());
            txtmodalidade.setText(curso.getModalidade());
            txtdenominacao.setText(curso.getDenomincacao());
            txthabilitacao.setText(curso.getHabilitacao());
            txtlocaloferta.setText(curso.getLocaloferta());
            txtturnos.setText(String.valueOf(curso.getTurnos()));
            txtvagas.setText(String.valueOf(curso.getVagas()));
            txtcargahoraria.setText(String.valueOf(curso.getCargahoraria()));
            txtregime.setText(curso.getRegime());
            txtperiodos.setText(String.valueOf(curso.getPeriodos()));
            cmbcoordenador.setSelectedItem(curso.getCoordenador());
            //txtcpf.setText(curso.getCpfcoord());
           // txttitulacao.setText(curso.getTitulacao());
           // txtdedicacao.setText(String.valueOf(curso.getTempodedicacao()));
            
           
          
            Component[] componentes =  JpanelCursos.getComponents(); // altere para o nome da variavel do seu painel
            for (Component componente : componentes) {
                componente.setEnabled(true);
            }
           txtcpf.setEnabled(false);
            txttitulacao.setEnabled(false);
            txtdedicacao.setEnabled(false); 
           btnnovo.setEnabled(false);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(false);
            btnalterar.setEnabled(true);
            btncancelar.setEnabled(true);
            txtcpf.setEnabled(false);
            txttitulacao.setEnabled(false);
            txtdedicacao.setEnabled(false);
            
        } catch (NegocioException ex) {
           // Logger.getLogger(JFIEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void cmbcoordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcoordenadorActionPerformed
        // TODO add your handling code here:
     if(cmbcoordenador.getItemCount()>0){      
        CoordenadoresBO bo = new CoordenadoresBO();
        try {
           
            Coordenadores coordenador=bo.consultar(cmbcoordenador.getSelectedItem().toString());
            txtcpf.setText(String.valueOf(coordenador.getCpfcoord()));
            txttitulacao.setText(coordenador.getTitulacao());
            txtdedicacao.setText(String.valueOf(coordenador.getDedicacao()));
            txtcpf.setEnabled(false);
            txttitulacao.setEnabled(false);
            txtdedicacao.setEnabled(false);
    }//GEN-LAST:event_cmbcoordenadorActionPerformed
    catch (NegocioException ex) {
           // Logger.getLogger(JFIEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    
     }
    


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Geral;
    private javax.swing.JPanel JpanelCursos;
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox<String> cmbcoordenador;
    private Apresentacao.JFIPPC jFIPPC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtcargahoraria;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtdedicacao;
    private javax.swing.JTextField txtdenominacao;
    private javax.swing.JTextField txthabilitacao;
    private javax.swing.JTextField txtlocaloferta;
    private javax.swing.JTextField txtmodalidade;
    private javax.swing.JTextField txtperiodos;
    private javax.swing.JTextField txtregime;
    private javax.swing.JTextField txttitulacao;
    private javax.swing.JTextField txttpcurso;
    private javax.swing.JTextField txtturnos;
    private javax.swing.JTextField txtvagas;
    // End of variables declaration//GEN-END:variables

   
}
