/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Entidades.Cargos;
import Entidades.Unidades;
import com.sun.javafx.tk.Toolkit;
import dados.DadosException;
import java.awt.Component;
import java.io.File;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import negocio.CargosBO;
import negocio.NegocioException;
import negocio.UnidadesBO;

/**
 *
 * @author Wallace
 */
public class JFICargos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFICargos
     */

    public JFICargos() {
        
        super();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngpordem = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnnova = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        JpanelCargos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcbo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        JRBId = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtbcargos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        JRBCargo = new javax.swing.JRadioButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Cargos");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1formFocusGained(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1formComponentShown(evt);
            }
        });

        btnnova.setText("NOVO");
        btnnova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovaActionPerformed(evt);
            }
        });

        btnsalvar.setText("SALVAR");
        btnsalvar.setEnabled(false);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnconsultar.setText("CONSULTAR");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btnalterar.setText("ALTERAR");
        btnalterar.setEnabled(false);
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        JpanelCargos.setEnabled(false);

        jLabel2.setText("Cargo");

        txtcargo.setEnabled(false);

        jLabel3.setText("CBO");

        txtcbo.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("CADASTRO DE CARGOS");

        jLabel1.setText("ID Cargo:");

        lblid.setText(" ");
        lblid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblidInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout JpanelCargosLayout = new javax.swing.GroupLayout(JpanelCargos);
        JpanelCargos.setLayout(JpanelCargosLayout);
        JpanelCargosLayout.setHorizontalGroup(
            JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelCargosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelCargosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblid))
                    .addGroup(JpanelCargosLayout.createSequentialGroup()
                        .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcargo)
                            .addComponent(txtcbo, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelCargosLayout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel5)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );
        JpanelCargosLayout.setVerticalGroup(
            JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelCargosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelCargosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        btngpordem.add(JRBId);
        JRBId.setText("ID");
        JRBId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBIdActionPerformed(evt);
            }
        });

        Jtbcargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cargo", "CBO"
            }
        ));
        Jtbcargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtbcargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtbcargos);

        jLabel4.setText("Ordenar por:");

        btngpordem.add(JRBCargo);
        JRBCargo.setText("Cargo");
        JRBCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JpanelCargos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(515, 515, 515))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnnova)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnconsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnalterar)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(JRBId)
                        .addGap(18, 18, 18)
                        .addComponent(JRBCargo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JpanelCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBId)
                    .addComponent(JRBCargo)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnova)
                    .addComponent(btnsalvar)
                    .addComponent(btnconsultar)
                    .addComponent(btnalterar)
                    .addComponent(btncancelar))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovaActionPerformed
        // TODO add your handling code here:
        btnnova.setEnabled(false);
        btnsalvar.setEnabled(true);
        btnconsultar.setEnabled(false);
        btnalterar.setEnabled(false);
        btncancelar.setEnabled(true);
        txtcargo.setText("");
        txtcbo.setText("");
        JpanelCargos.setEnabled(true);
        Jtbcargos.setEnabled(false);
        Component[] componentes =  JpanelCargos.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(true);
            

    }//GEN-LAST:event_btnnovaActionPerformed
        
    }
    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        Cargos cargo= new Cargos();
        cargo.setCargo(txtcargo.getText());
        cargo.setCbo(Integer.parseInt(txtcbo.getText()));
        CargosBO bo = new CargosBO();
        try{
            if(cargo.getIdcargo()==0){
                bo.inserir(cargo);
                btnnova.setEnabled(true);
                btnsalvar.setEnabled(false);
                btnconsultar.setEnabled(true);
                btnalterar.setEnabled(false);
                btncancelar.setEnabled(false);
                txtcargo.setText("");
                txtcbo.setText("");
                lblid.setText("");
                JpanelCargos.setEnabled(true);
                Jtbcargos.setEnabled(true);
                
                Component[] componentes =  JpanelCargos.getComponents(); // altere para o nome da variavel do seu painel
                for (Component componente : componentes) {
                    componente.setEnabled(false);
                }
                DefaultTableModel model = (DefaultTableModel) Jtbcargos.getModel();
                model.setRowCount(0);
            }

        }catch(NegocioException e){
            JOptionPane.showMessageDialog(null,e.getMessage() ,"Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
       
            
        int idconsulta = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da cargo"));
        CargosBO bo = new CargosBO();
        try {
             DefaultTableModel model = (DefaultTableModel) Jtbcargos.getModel();
             model.setRowCount(0);
            Cargos cargo=bo.consultar(idconsulta);
            lblid.setText(Integer.toString(cargo.getIdcargo()));
            txtcargo.setText(cargo.getCargo());
            txtcbo.setText(Integer.toString(cargo.getCbo()));
            btnnova.setEnabled(false);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(false);
            btnalterar.setEnabled(true);
            btncancelar.setEnabled(true);
            Jtbcargos.setEnabled(false);
            Component[] componentes =  JpanelCargos.getComponents(); // altere para o nome da variavel do seu painel
            for (Component componente : componentes) {
                componente.setEnabled(true);
            }
            Jtbcargos.setEnabled(false);
            UnidadesBO bouni=new UnidadesBO();
            
        } catch (NegocioException ex) {
           // Logger.getLogger(JFIEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Jtbcargos.getModel();
        model.setRowCount(0);
        int idconsulta = Integer.parseInt(lblid.getText());
        Cargos cargo= new Cargos();
        cargo.setIdcargo(idconsulta);
        cargo.setCargo(txtcargo.getText());
        cargo.setCbo(Integer.parseInt(txtcbo.getText()));
        CargosBO bo = new CargosBO();
        try {

            bo.alterar(cargo);
            btnnova.setEnabled(true);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(true);
            btnalterar.setEnabled(false);
            btncancelar.setEnabled(false);
            
            
            txtcargo.setText("");
            txtcbo.setText("");
            lblid.setText("");
            JpanelCargos.setEnabled(true);
            Jtbcargos.setEnabled(true);

            Component[] componentes =  JpanelCargos.getComponents(); // altere para o nome da variavel do seu painel
            for (Component componente : componentes) {
                componente.setEnabled(false);
            }
        } catch (NegocioException ex) {
            //Logger.getLogger(JFEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnalterarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        btnnova.setEnabled(true);
        btnsalvar.setEnabled(false);
        btnconsultar.setEnabled(true);
        btnalterar.setEnabled(false);
        btncancelar.setEnabled(false);
        txtcargo.setText("");
        txtcbo.setText("");
        JpanelCargos.setEnabled(true);
        Jtbcargos.setEnabled(false);
        lblid.setText("");
        Jtbcargos.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel) Jtbcargos.getModel();
        model.setRowCount(0);
        Component[] componentes =  JpanelCargos.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(false);
    }//GEN-LAST:event_btncancelarActionPerformed
    }
    private void jPanel1formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1formFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1formFocusGained

    private void jPanel1formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1formComponentShown

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
         
                  
        
            
    }//GEN-LAST:event_formInternalFrameActivated

    private void lblidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblidInputMethodTextChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_lblidInputMethodTextChanged

    private void JRBIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBIdActionPerformed
        // TODO add your handling code here:
        CargosBO bo=new CargosBO();
            try{
                List<Cargos> lista=bo.listar("idcargo");
                DefaultTableModel model = (DefaultTableModel) Jtbcargos.getModel();
                model.setRowCount(0);
                for(Cargos cargo:lista){
                   
                
                    model.addRow(new Object[]{cargo.getIdcargo(),cargo.getCargo(),cargo.getCbo()});
                }
            }catch(NegocioException ex){
            
            }
    }//GEN-LAST:event_JRBIdActionPerformed

    private void JRBCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBCargoActionPerformed
        // TODO add your handling code here:
           CargosBO bo=new CargosBO();
            try{
                List<Cargos> lista=bo.listar("cargo");
                DefaultTableModel model = (DefaultTableModel) Jtbcargos.getModel();
                model.setRowCount(0);
                for(Cargos cargo:lista){
                   
                
                    model.addRow(new Object[]{cargo.getIdcargo(),cargo.getCargo(),cargo.getCbo()});
                    
                }
            }catch(NegocioException ex){
            
            }
    }//GEN-LAST:event_JRBCargoActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void JtbcargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtbcargosMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Jtbcargos.getModel();
        lblid.setText(model.getValueAt(Jtbcargos.getSelectedRow(),0).toString());
        txtcargo.setText(model.getValueAt(Jtbcargos.getSelectedRow(),1).toString());
        txtcbo.setText(model.getValueAt(Jtbcargos.getSelectedRow(),2).toString());
          btnnova.setEnabled(false);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(false);
            btnalterar.setEnabled(true);
            btncancelar.setEnabled(true);
            Jtbcargos.setEnabled(false);
             Component[] componentes =  JpanelCargos.getComponents(); // altere para o nome da variavel do seu painel
            for (Component componente : componentes) {
            componente.setEnabled(true);
        }  
    }//GEN-LAST:event_JtbcargosMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRBCargo;
    private javax.swing.JRadioButton JRBId;
    private javax.swing.JPanel JpanelCargos;
    private javax.swing.JTable Jtbcargos;
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.ButtonGroup btngpordem;
    private javax.swing.JButton btnnova;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcbo;
    // End of variables declaration//GEN-END:variables

   
}
