/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Entidades.Escalas;
import Entidades.Unidades;
import com.sun.javafx.tk.Toolkit;
import dados.DadosException;
import java.awt.Component;
import java.io.File;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import negocio.EscalasBO;
import negocio.NegocioException;
import negocio.UnidadesBO;

/**
 *
 * @author Wallace
 */
public class JFIEscalas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFIEscalas
     */

    public JFIEscalas() {
        
        super();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngpordem = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnnova = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        JpanelEscalas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtescala = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        JRBId = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        JRBEscala = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtbescalas = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Escalas");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1formFocusGained(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1formComponentShown(evt);
            }
        });

        btnnova.setText("NOVO");
        btnnova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovaActionPerformed(evt);
            }
        });

        btnsalvar.setText("SALVAR");
        btnsalvar.setEnabled(false);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnconsultar.setText("CONSULTAR");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btnalterar.setText("ALTERAR");
        btnalterar.setEnabled(false);
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        JpanelEscalas.setEnabled(false);

        jLabel2.setText("Escala:");

        txtescala.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("CADASTRO DE ESCALAS");

        jLabel1.setText("ID Escala:");

        lblid.setText(" ");
        lblid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblidInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout JpanelEscalasLayout = new javax.swing.GroupLayout(JpanelEscalas);
        JpanelEscalas.setLayout(JpanelEscalasLayout);
        JpanelEscalasLayout.setHorizontalGroup(
            JpanelEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelEscalasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblid))
                    .addGroup(JpanelEscalasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtescala, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(453, Short.MAX_VALUE))
            .addGroup(JpanelEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelEscalasLayout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel5)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );
        JpanelEscalasLayout.setVerticalGroup(
            JpanelEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelEscalasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(JpanelEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtescala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(JpanelEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelEscalasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        btngpordem.add(JRBId);
        JRBId.setText("ID");
        JRBId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBIdActionPerformed(evt);
            }
        });

        jLabel4.setText("Ordenar por:");

        btngpordem.add(JRBEscala);
        JRBEscala.setText("Escala");
        JRBEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBEscalaActionPerformed(evt);
            }
        });

        Jtbescalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cargo"
            }
        ));
        Jtbescalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtbescalasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Jtbescalas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JpanelEscalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(515, 515, 515))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnnova)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnconsultar)
                                .addGap(18, 18, 18)
                                .addComponent(btnalterar)
                                .addGap(18, 18, 18)
                                .addComponent(btncancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addGap(39, 39, 39)
                                .addComponent(JRBId)
                                .addGap(18, 18, 18)
                                .addComponent(JRBEscala))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JpanelEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBId)
                    .addComponent(JRBEscala)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnova)
                    .addComponent(btnsalvar)
                    .addComponent(btnconsultar)
                    .addComponent(btnalterar)
                    .addComponent(btncancelar))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1338, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovaActionPerformed
        // TODO add your handling code here:
        btnnova.setEnabled(false);
        btnsalvar.setEnabled(true);
        btnconsultar.setEnabled(false);
        btnalterar.setEnabled(false);
        btncancelar.setEnabled(true);
        txtescala.setText("");
        
        JpanelEscalas.setEnabled(true);
        Jtbescalas.setEnabled(false);
        Component[] componentes =  JpanelEscalas.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(true);
            

    }//GEN-LAST:event_btnnovaActionPerformed
        
    }
    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        Escalas escala= new Escalas();
        escala.setEscala(txtescala.getText());
        
        EscalasBO bo = new EscalasBO();
        try{
            if(escala.getIdescala()==0){
                bo.inserir(escala);
                btnnova.setEnabled(true);
                btnsalvar.setEnabled(false);
                btnconsultar.setEnabled(true);
                btnalterar.setEnabled(false);
                btncancelar.setEnabled(false);
                txtescala.setText("");
              
                lblid.setText("");
                JpanelEscalas.setEnabled(true);
                Jtbescalas.setEnabled(true);
                
                Component[] componentes =  JpanelEscalas.getComponents(); // altere para o nome da variavel do seu painel
                for (Component componente : componentes) {
                    componente.setEnabled(false);
                }
                DefaultTableModel model = (DefaultTableModel) Jtbescalas.getModel();
                model.setRowCount(0);
            }

        }catch(NegocioException e){
            JOptionPane.showMessageDialog(null,e.getMessage() ,"Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
       
            
        int idconsulta = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da escala"));
        EscalasBO bo = new EscalasBO();
        try {
             DefaultTableModel model = (DefaultTableModel) Jtbescalas.getModel();
             model.setRowCount(0);
            Escalas escala=bo.consultar(idconsulta);
            lblid.setText(Integer.toString(escala.getIdescala()));
            txtescala.setText(escala.getEscala());
            
            btnnova.setEnabled(false);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(false);
            btnalterar.setEnabled(true);
            btncancelar.setEnabled(true);
            Jtbescalas.setEnabled(false);
            Component[] componentes =  JpanelEscalas.getComponents(); // altere para o nome da variavel do seu painel
            for (Component componente : componentes) {
                componente.setEnabled(true);
            }
            Jtbescalas.setEnabled(false);
            
            
        } catch (NegocioException ex) {
           // Logger.getLogger(JFIEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Jtbescalas.getModel();
        model.setRowCount(0);
        int idconsulta = Integer.parseInt(lblid.getText());
        Escalas escala= new Escalas();
        escala.setIdescala(idconsulta);
        escala.setEscala(txtescala.getText());
        
        EscalasBO bo = new EscalasBO();
        try {

            bo.alterar(escala);
            btnnova.setEnabled(true);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(true);
            btnalterar.setEnabled(false);
            btncancelar.setEnabled(false);
            
            
            txtescala.setText("");
            
            lblid.setText("");
            JpanelEscalas.setEnabled(true);
            Jtbescalas.setEnabled(true);

            Component[] componentes =  JpanelEscalas.getComponents(); // altere para o nome da variavel do seu painel
            for (Component componente : componentes) {
                componente.setEnabled(false);
            }
        } catch (NegocioException ex) {
            //Logger.getLogger(JFEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnalterarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        btnnova.setEnabled(true);
        btnsalvar.setEnabled(false);
        btnconsultar.setEnabled(true);
        btnalterar.setEnabled(false);
        btncancelar.setEnabled(false);
        txtescala.setText("");
        
        JpanelEscalas.setEnabled(true);
        Jtbescalas.setEnabled(false);
        lblid.setText("");
        Jtbescalas.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel) Jtbescalas.getModel();
        model.setRowCount(0);
        Component[] componentes =  JpanelEscalas.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(false);
    }//GEN-LAST:event_btncancelarActionPerformed
    }
    private void jPanel1formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1formFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1formFocusGained

    private void jPanel1formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1formComponentShown

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
         
                  
        
            
    }//GEN-LAST:event_formInternalFrameActivated

    private void lblidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblidInputMethodTextChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_lblidInputMethodTextChanged

    private void JRBIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBIdActionPerformed
        // TODO add your handling code here:
        EscalasBO bo=new EscalasBO();
            try{
                List<Escalas> lista=bo.listar("idescala");
                DefaultTableModel model = (DefaultTableModel) Jtbescalas.getModel();
                model.setRowCount(0);
                for(Escalas escala:lista){
                   
                
                    model.addRow(new Object[]{escala.getIdescala(),escala.getEscala()});
                }
            }catch(NegocioException ex){
            
            }
    }//GEN-LAST:event_JRBIdActionPerformed

    private void JRBEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBEscalaActionPerformed
        // TODO add your handling code here:
           EscalasBO bo=new EscalasBO();
            try{
                List<Escalas> lista=bo.listar("escala");
                DefaultTableModel model = (DefaultTableModel) Jtbescalas.getModel();
                model.setRowCount(0);
                for(Escalas escala:lista){
                   
                
                    model.addRow(new Object[]{escala.getIdescala(),escala.getEscala()});
                    
                }
            }catch(NegocioException ex){
            
            }
    }//GEN-LAST:event_JRBEscalaActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void JtbescalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtbescalasMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Jtbescalas.getModel();
        lblid.setText(model.getValueAt(Jtbescalas.getSelectedRow(),0).toString());
        txtescala.setText(model.getValueAt(Jtbescalas.getSelectedRow(),1).toString());
        ;
        btnnova.setEnabled(false);
        btnsalvar.setEnabled(false);
        btnconsultar.setEnabled(false);
        btnalterar.setEnabled(true);
        btncancelar.setEnabled(true);
        Jtbescalas.setEnabled(false);
        Component[] componentes =  JpanelEscalas.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(true);
        }
    }//GEN-LAST:event_JtbescalasMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRBEscala;
    private javax.swing.JRadioButton JRBId;
    private javax.swing.JPanel JpanelEscalas;
    private javax.swing.JTable Jtbescalas;
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.ButtonGroup btngpordem;
    private javax.swing.JButton btnnova;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtescala;
    // End of variables declaration//GEN-END:variables

   
}
