/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Entidades.Empresas;
import Entidades.Unidades;
import com.sun.javafx.tk.Toolkit;
import dados.DadosException;
import java.awt.Component;
import java.io.File;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import negocio.EmpresasBO;
import negocio.NegocioException;
import negocio.UnidadesBO;

/**
 *
 * @author Wallace
 */
public class JFIEmpresas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFIEmpresas
     */
    public static JDUnidades unidades;
    public static JDListaEmpresas empresas;
    public JFIEmpresas() {
        super();
        initComponents();
    }
public void mostraunidades(){
    unidades= new JDUnidades(this,true);
    unidades.setLocationRelativeTo(null);
    unidades.setVisible(true);
  
}
public void mostraempresas(){
    empresas= new JDListaEmpresas(this,true);
    empresas.setLocationRelativeTo(null);
    empresas.setVisible(true);
  
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnnova = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        JpanelEmpresas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtrazaosocial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnomefantasia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlocalimagem = new javax.swing.JTextField();
        btnlocalizar = new javax.swing.JButton();
        chkativa = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtbunidades = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        btnaddunidade = new javax.swing.JButton();
        btnlistar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Empresas");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1formFocusGained(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1formComponentShown(evt);
            }
        });

        btnnova.setText("NOVA");
        btnnova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovaActionPerformed(evt);
            }
        });

        btnsalvar.setText("SALVAR");
        btnsalvar.setEnabled(false);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnconsultar.setText("CONSULTAR");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btnalterar.setText("ALTERAR");
        btnalterar.setEnabled(false);
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        JpanelEmpresas.setEnabled(false);

        jLabel2.setText("Razão Social:");

        txtrazaosocial.setEnabled(false);

        jLabel3.setText("Nome Fantasia:");

        txtnomefantasia.setEnabled(false);

        jLabel4.setText("Logo:");

        txtlocalimagem.setEditable(false);
        txtlocalimagem.setText("txtlocalimagem");
        txtlocalimagem.setEnabled(false);

        btnlocalizar.setText("Localizar");
        btnlocalizar.setEnabled(false);
        btnlocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocalizarActionPerformed(evt);
            }
        });

        chkativa.setSelected(true);
        chkativa.setText("ATIVA");
        chkativa.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("UNIDADES");

        Jtbunidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Unidade", "Ativa", "Matriz"
            }
        ));
        Jtbunidades.setEnabled(false);
        jScrollPane1.setViewportView(Jtbunidades);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("CADASTRO DE EMPRESAS");

        jLabel1.setText("ID Empresa:");

        lblid.setText(" ");
        lblid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblidInputMethodTextChanged(evt);
            }
        });

        btnaddunidade.setText("+");
        btnaddunidade.setEnabled(false);
        btnaddunidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddunidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelEmpresasLayout = new javax.swing.GroupLayout(JpanelEmpresas);
        JpanelEmpresas.setLayout(JpanelEmpresasLayout);
        JpanelEmpresasLayout.setHorizontalGroup(
            JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblid))
                    .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnaddunidade))
                    .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                        .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                                .addComponent(txtlocalimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlocalizar)
                                .addGap(18, 18, 18)
                                .addComponent(chkativa))
                            .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtrazaosocial)
                                .addComponent(txtnomefantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel6)))
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel5)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );
        JpanelEmpresasLayout.setVerticalGroup(
            JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnomefantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlocalimagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlocalizar)
                    .addComponent(chkativa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelEmpresasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddunidade)
                        .addGap(93, 93, 93))))
            .addGroup(JpanelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelEmpresasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );

        btnlistar.setText("LISTAR");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnova)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnconsultar)
                .addGap(9, 9, 9)
                .addComponent(btnlistar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnalterar)
                .addGap(18, 18, 18)
                .addComponent(btncancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JpanelEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(515, 515, 515))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JpanelEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnova)
                    .addComponent(btnsalvar)
                    .addComponent(btnconsultar)
                    .addComponent(btnalterar)
                    .addComponent(btncancelar)
                    .addComponent(btnlistar))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovaActionPerformed
        // TODO add your handling code here:
        btnnova.setEnabled(false);
        btnsalvar.setEnabled(true);
        btnconsultar.setEnabled(false);
        btnalterar.setEnabled(false);
        btncancelar.setEnabled(true);
        txtrazaosocial.setText("");
        txtnomefantasia.setText("");
        txtlocalimagem.setText("");
        btnlistar.setEnabled(false);
        JpanelEmpresas.setEnabled(true);
        Jtbunidades.setEnabled(false);
        Component[] componentes =  JpanelEmpresas.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(true);

    }//GEN-LAST:event_btnnovaActionPerformed
        btnaddunidade.setEnabled(false);
    }
    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        Empresas empresa= new Empresas();
        empresa.setRazao(txtrazaosocial.getText());
        empresa.setNmfantasia(txtnomefantasia.getText());
        empresa.setLogo(txtlocalimagem.getText());
        empresa.setAtiva(chkativa.isSelected());
        EmpresasBO bo = new EmpresasBO();
        try{
            if(empresa.getIdempresa()==0){
                bo.inserir(empresa);
                btnnova.setEnabled(true);
                btnsalvar.setEnabled(false);
                btnconsultar.setEnabled(true);
                btnalterar.setEnabled(false);
                btncancelar.setEnabled(false);
                txtrazaosocial.setText("");
                txtnomefantasia.setText("");
                txtlocalimagem.setText("");
                JpanelEmpresas.setEnabled(true);
                Jtbunidades.setEnabled(false);
                btnlistar.setEnabled(true);
                Component[] componentes =  JpanelEmpresas.getComponents(); // altere para o nome da variavel do seu painel
                for (Component componente : componentes) {
                    componente.setEnabled(false);
                }
                DefaultTableModel model = (DefaultTableModel) Jtbunidades.getModel();
                model.setRowCount(0);
            }

        }catch(NegocioException e){
            JOptionPane.showMessageDialog(null,e.getMessage() ,"Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
       
            
        int idconsulta = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da empresa"));
        EmpresasBO bo = new EmpresasBO();
        try {
             DefaultTableModel model = (DefaultTableModel) Jtbunidades.getModel();
             model.setRowCount(0);
            Empresas empresa=bo.consultar(idconsulta);
            lblid.setText(Integer.toString(empresa.getIdempresa()));
            txtrazaosocial.setText(empresa.getRazao());
            txtnomefantasia.setText(empresa.getNmfantasia());
            txtlocalimagem.setText(empresa.getLogo());
            chkativa.setSelected(empresa.isAtiva());
            btnnova.setEnabled(false);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(false);
            btnalterar.setEnabled(true);
            btncancelar.setEnabled(true);
            btnlistar.setEnabled(false);
            Component[] componentes =  JpanelEmpresas.getComponents(); // altere para o nome da variavel do seu painel
            for (Component componente : componentes) {
                componente.setEnabled(true);
            }
            Jtbunidades.setEnabled(false);
            UnidadesBO bouni=new UnidadesBO();
            try{
                List<Unidades> lista=bouni.listar(Integer.parseInt(lblid.getText()));
                for(Unidades unidade:lista){
                   
                //Object[] linha = //alguma linha
 
                //model.addRow(linha);
                    model.addRow(new Object[]{unidade.getCNPJ(),unidade.getNomeUnidade(),convertbol(unidade.isAtiva()),convertbol(unidade.isMatriz())});
                }
            }catch(NegocioException ex){
            
            } catch (DadosException ex) {
                Logger.getLogger(JFIEmpresas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (NegocioException ex) {
           // Logger.getLogger(JFIEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Jtbunidades.getModel();
        model.setRowCount(0);
        int idconsulta = Integer.parseInt(lblid.getText());
        Empresas empresa= new Empresas();
        empresa.setIdempresa(idconsulta);
        empresa.setRazao(txtrazaosocial.getText());
        empresa.setNmfantasia(txtnomefantasia.getText());
        empresa.setLogo(txtlocalimagem.getText());
        empresa.setAtiva(chkativa.isSelected());
        EmpresasBO bo = new EmpresasBO();
        try {

            bo.alterar(empresa);
            btnnova.setEnabled(true);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(true);
            btnalterar.setEnabled(false);
            btncancelar.setEnabled(false);
            btnlistar.setEnabled(true);
            
            txtrazaosocial.setText("");
            txtnomefantasia.setText("");
            txtlocalimagem.setText("");
            lblid.setText("");
            JpanelEmpresas.setEnabled(true);
            Jtbunidades.setEnabled(false);

            Component[] componentes =  JpanelEmpresas.getComponents(); // altere para o nome da variavel do seu painel
            for (Component componente : componentes) {
                componente.setEnabled(false);
            }
        } catch (NegocioException ex) {
            //Logger.getLogger(JFEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnalterarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        btnnova.setEnabled(true);
        btnsalvar.setEnabled(false);
        btnconsultar.setEnabled(true);
        btnalterar.setEnabled(false);
        btncancelar.setEnabled(false);
        txtrazaosocial.setText("");
        txtnomefantasia.setText("");
        txtlocalimagem.setText("");
        JpanelEmpresas.setEnabled(true);
        Jtbunidades.setEnabled(false);
        lblid.setText("");
        btnlistar.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel) Jtbunidades.getModel();
        model.setRowCount(0);
        Component[] componentes =  JpanelEmpresas.getComponents(); // altere para o nome da variavel do seu painel
        for (Component componente : componentes) {
            componente.setEnabled(false);
    }//GEN-LAST:event_btncancelarActionPerformed
    }
    private void btnlocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocalizarActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i==1){
            txtlocalimagem.setText("");
        } else {
            File arquivo = file.getSelectedFile();
            txtlocalimagem.setText(arquivo.getPath());
        }
    }//GEN-LAST:event_btnlocalizarActionPerformed

    private void btnaddunidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddunidadeActionPerformed
        // TODO add your handling code here:
        mostraunidades();
        

    }//GEN-LAST:event_btnaddunidadeActionPerformed

    private void jPanel1formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1formFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1formFocusGained

    private void jPanel1formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1formComponentShown

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
        mostraempresas();
    }//GEN-LAST:event_btnlistarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
         
                  
        
            
    }//GEN-LAST:event_formInternalFrameActivated

    private void lblidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblidInputMethodTextChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_lblidInputMethodTextChanged

    public JLabel getLblid() {
        return lblid;
    }

    public void setLblid(String lblid) {
        this.lblid.setText(lblid);
            EmpresasBO bo = new EmpresasBO();
        try {
             DefaultTableModel model = (DefaultTableModel) Jtbunidades.getModel();
             model.setRowCount(0);
                if(!lblid.isEmpty()){
                    Empresas empresa=bo.consultar(Integer.parseInt(lblid));
                    //lblid.setText(Integer.toString(empresa.getIdempresa()));
                    txtrazaosocial.setText(empresa.getRazao());
                    txtnomefantasia.setText(empresa.getNmfantasia());
                    txtlocalimagem.setText(empresa.getLogo());
                    chkativa.setSelected(empresa.isAtiva());
                    btnnova.setEnabled(false);
                    btnsalvar.setEnabled(false);
                    btnconsultar.setEnabled(false);
                    btnalterar.setEnabled(true);
                    btncancelar.setEnabled(true);
                    btnlistar.setEnabled(false);
                    Component[] componentes =  JpanelEmpresas.getComponents(); // altere para o nome da variavel do seu painel
                    for (Component componente : componentes) {
                        componente.setEnabled(true);
                    }
                    UnidadesBO bouni=new UnidadesBO();
                    try{
                        List<Unidades> lista=bouni.listar(Integer.parseInt(lblid));
                        for(Unidades unidade:lista){
                            
                            //Object[] linha = //alguma linha
                            
                            //model.addRow(linha);
                            model.addRow(new Object[]{unidade.getCNPJ(),unidade.getNomeUnidade(),convertbol(unidade.isAtiva()),convertbol(unidade.isMatriz())});
                        }
                    }catch(NegocioException ex){

                    } catch (DadosException ex) {
                        Logger.getLogger(JFIEmpresas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                }
        }    
                catch (NegocioException ex) {
                   // Logger.getLogger(JFIEmpresa.class.getName()).log(Level.SEVERE, null, ex);
                }
    }

    public JTextField getTxtnomefantasia() {
        return txtnomefantasia;
    }

public String convertbol(boolean valor){
     if(valor){
        return ("SIM");
     }else{
         return("NÃO");
     }   
    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelEmpresas;
    private javax.swing.JTable Jtbunidades;
    private javax.swing.JButton btnaddunidade;
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnlistar;
    private javax.swing.JButton btnlocalizar;
    private javax.swing.JButton btnnova;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JCheckBox chkativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtlocalimagem;
    private javax.swing.JTextField txtnomefantasia;
    private javax.swing.JTextField txtrazaosocial;
    // End of variables declaration//GEN-END:variables

   
}
